// AUTHENTICATION TYPES
export const LOGOUT_USER = 'LOGOUT_USER'
export const AUTHENTICATED = 'AUTHENTICATED'
export const UNAUTHENTICATED ='UNAUTHENTICATED'
export const LOADING = 'LOADING'
export const LOADED = 'LOADED'
// DATA TYPES
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS'
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED'
export const ON_ADMIN_VIEW = 'ON_ADMIN_VIEW'
export const OUT_ADMIN_VIEW = 'OUT_ADMIN_VIEW'
// CART TYPES
export const SET_CART = 'SET_CART'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY'